### ISSUE TITLE
RDF4J validator not working?

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/data-validator#11]
When testing #8 , I [added the RDF4J validator](https://github.com/mff-uk/data-specification-vocabulary/commit/eba053d9e38f3e343af039169db798c444eec75f), but the validation now [fails](https://github.com/mff-uk/data-specification-vocabulary/actions/runs/8374631954/job/22930300556) on:
```
Can't load configuration.
12:0[7](https://github.com/mff-uk/data-specification-vocabulary/actions/runs/8374631954/job/22930300556#step:4:8):32 [main] INFO  c.m.d.cli.AppEntry - Exception.
java.io.IOException: Missing validator type for node1hpgehia[8](https://github.com/mff-uk/data-specification-vocabulary/actions/runs/8374631954/job/22930300556#step:4:9)x7
	at cz.mvcr.datavalidator.cli.ConfigurationAdapter.onRuleValidator(ConfigurationAdapter.java:124)
	at cz.mvcr.datavalidator.cli.ConfigurationAdapter.onRule(ConfigurationAdapter.java:[10](https://github.com/mff-uk/data-specification-vocabulary/actions/runs/8374631954/job/22930300556#step:4:11)4)
	at cz.mvcr.datavalidator.cli.ConfigurationAdapter.onConfiguration(ConfigurationAdapter.java:70)
	at cz.mvcr.datavalidator.cli.ConfigurationAdapter.load(ConfigurationAdapter.java:37)
	at cz.mvcr.datavalidator.cli.AppEntry.loadConfiguration(AppEntry.java:[11](https://github.com/mff-uk/data-specification-vocabulary/actions/runs/8374631954/job/22930300556#step:4:12)4)
	at cz.mvcr.datavalidator.cli.AppEntry.run(AppEntry.java:50)
	at cz.mvcr.datavalidator.cli.AppEntry.main(AppEntry.java:35)
```

**Comment by skodapetr** [comment]
You need to change `uses: datagov-cz/data-validator/github@master` to `uses: datagov-cz/data-validator/github@main`.

**Comment by jakubklimek** [comment]
That results in:
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' for action 'datagov-cz/data-validator/github@main'.
```
see https://github.com/mff-uk/data-specification-vocabulary/actions/runs/8432402719

**Comment by skodapetr** [comment]
Should be fixed by now with https://github.com/datagov-cz/data-validator/commit/1b640a6e4a7af040e9e927b56e5c7b015242804e .
